import Navbar from "../components/navbar/Navbar"
import "./home.scss"
const Home = () => {
  return (
    <div className="home">
        <Navbar/>
        <img 
        width="100%"
        src="https://images.squarespace-cdn.com/content/v1/58757367b3db2b3e1ec9477d/1595386216368-ZMPQY7Q47JFLHD7ZR8KY/19052020_the_old_guard_netflix_poster_feat.jpg?" 
        alt="" />
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas assumenda obcaecati, ea voluptatum modi delectus asperiores, laudantium temporibus maiores, necessitatibus excepturi voluptatem! Voluptas, dolor molestias? Minus maiores veniam facere asperiores.ß
    </div>
  )
}

export default Home